[project]
name = "ai-mock-interview"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymupdf>=1.28.2",
    "google-genai>=1.0.0",
    "python-dotenv>=1.0.0",
    "fastapi>=0.141.1",
    "uvicorn>=0.53.0",
    "python-multipart>=0.0.32",
    "supabase>=2.31.0",
    "langgraph>=0.2.0",
]
