-- Migration to add structured profile metadata and contact information
-- safely to the existing resumes table.

-- 1. Add email, phone, location for contact fields.
ALTER TABLE resumes
ADD COLUMN IF NOT EXISTS email TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS location TEXT;

-- 2. Add a JSONB column for the flexible profile metadata.
-- This column will store the following fields generated by the Gemini analyzer:
-- - potential_interview_topics (list of strings)
-- - expertise_areas (list of strings)
-- - achievements (list of strings)
-- - publications (list of strings)
-- - competitive_programming (object)
-- - languages (list of strings)
-- - interests (list of strings)
ALTER TABLE resumes
ADD COLUMN IF NOT EXISTS profile_metadata JSONB DEFAULT '{}'::jsonb;
