"""
role_catalogue.py

Central catalog of all available mock interview roles (50 roles).
"""

ROLE_CATALOGUE = [
    {
        "id": "role_ml_eng",
        "title": "ML Engineer",
        "category": "AI & ML",
        "department": "Machine Learning & AI",
        "difficulty": "Senior",
        "description": "Design and deploy state-of-the-art machine learning models, vector pipelines, and evaluation engines with PyTorch and FastAPI.",
        "requiredSkills": ["Python", "Machine Learning", "PyTorch", "FastAPI"],
        "preferredSkills": ["Scikit-learn", "TensorFlow", "Pandas"],
        "relatedSkills": ["Docker", "SQL", "Git"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Brain",
        "featured": True,
    },
    {
        "id": "role_data_scientist",
        "title": "Data Scientist",
        "category": "AI & ML",
        "department": "Analytics & Modeling",
        "difficulty": "Senior",
        "description": "Drive actionable predictive modeling, statistical hypothesis testing, feature engineering, and metric attribution.",
        "requiredSkills": ["Python", "Statistics", "Scikit-learn", "Pandas"],
        "preferredSkills": ["SQL", "NumPy", "TensorFlow"],
        "relatedSkills": ["Git", "Machine Learning", "Data Visualization"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "LineChart",
        "featured": False,
    },
    {
        "id": "role_ai_eng",
        "title": "AI Engineer",
        "category": "AI & ML",
        "department": "AI Products",
        "difficulty": "Mid-Level",
        "description": "Build AI agents, integrate LLMs via LangChain/LangGraph, and optimize RAG pipelines.",
        "requiredSkills": ["Python", "LLMs", "LangChain", "OpenAI API"],
        "preferredSkills": ["Vector Databases", "FastAPI", "Prompt Engineering"],
        "relatedSkills": ["Docker", "Git", "Machine Learning"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Cpu",
        "featured": True,
    },
    {
        "id": "role_nlp_eng",
        "title": "NLP Engineer",
        "category": "AI & ML",
        "department": "Machine Learning & AI",
        "difficulty": "Senior",
        "description": "Develop text analysis pipelines, fine-tune transformer models, and build conversational interfaces.",
        "requiredSkills": ["Python", "NLP", "PyTorch", "Transformers"],
        "preferredSkills": ["HuggingFace", "Spacy", "NLTK"],
        "relatedSkills": ["Machine Learning", "FastAPI", "Docker"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Brain",
        "featured": False,
    },
    {
        "id": "role_cv_eng",
        "title": "Computer Vision Engineer",
        "category": "AI & ML",
        "department": "Machine Learning & AI",
        "difficulty": "Senior",
        "description": "Design image processing algorithms, object detection, and segmentation models.",
        "requiredSkills": ["Python", "Computer Vision", "OpenCV", "PyTorch"],
        "preferredSkills": ["TensorFlow", "Deep Learning", "CUDA"],
        "relatedSkills": ["Machine Learning", "C++", "Git"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Brain",
        "featured": False,
    },
    {
        "id": "role_mlops",
        "title": "MLOps Engineer",
        "category": "AI & ML",
        "department": "AI Infrastructure",
        "difficulty": "Senior",
        "description": "Automate machine learning lifecycles, model deployment, and monitoring systems.",
        "requiredSkills": ["Python", "Docker", "Kubernetes", "CI/CD"],
        "preferredSkills": ["MLflow", "AWS", "GCP"],
        "relatedSkills": ["Machine Learning", "Terraform", "Git"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Server",
        "featured": False,
    },
    {
        "id": "role_prompt_eng",
        "title": "Prompt Engineer",
        "category": "AI & ML",
        "department": "AI Products",
        "difficulty": "Junior",
        "description": "Design, optimize, and test LLM prompts for various generative AI applications.",
        "requiredSkills": ["Python", "Prompt Engineering", "LLMs"],
        "preferredSkills": ["OpenAI API", "LangChain", "Data Analysis"],
        "relatedSkills": ["Git", "Communication", "Creative Writing"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Code",
        "featured": False,
    },
    {
        "id": "role_ai_researcher",
        "title": "AI Research Scientist",
        "category": "AI & ML",
        "department": "R&D",
        "difficulty": "Staff/Architect",
        "description": "Push the boundaries of deep learning, invent new architectures, and publish papers.",
        "requiredSkills": ["Python", "Deep Learning", "PyTorch", "Mathematics"],
        "preferredSkills": ["TensorFlow", "Statistics", "Research"],
        "relatedSkills": ["Machine Learning", "Algorithms", "C++"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Brain",
        "featured": False,
    },
    {
        "id": "role_rl_eng",
        "title": "Reinforcement Learning Engineer",
        "category": "AI & ML",
        "department": "R&D",
        "difficulty": "Senior",
        "description": "Develop autonomous agents and simulate environments for deep reinforcement learning.",
        "requiredSkills": ["Python", "Reinforcement Learning", "PyTorch"],
        "preferredSkills": ["TensorFlow", "Algorithms", "Mathematics"],
        "relatedSkills": ["Machine Learning", "C++", "Git"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Cpu",
        "featured": False,
    },
    {
        "id": "role_genai_architect",
        "title": "Generative AI Architect",
        "category": "AI & ML",
        "department": "AI Architecture",
        "difficulty": "Staff/Architect",
        "description": "Design enterprise-wide GenAI strategies, RAG systems, and AI security protocols.",
        "requiredSkills": ["Python", "System Design", "LLMs", "Vector Databases"],
        "preferredSkills": ["LangChain", "AWS", "GCP"],
        "relatedSkills": ["Machine Learning", "Security", "FastAPI"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Brain",
        "featured": True,
    },
    {
        "id": "role_data_eng",
        "title": "Data Engineer",
        "category": "Data",
        "department": "Data Platform",
        "difficulty": "Mid-Level",
        "description": "Architect robust ETL pipelines, data warehouses, and distributed processing jobs.",
        "requiredSkills": ["Python", "SQL", "Apache Spark", "Airflow"],
        "preferredSkills": ["PostgreSQL", "AWS", "GCP"],
        "relatedSkills": ["Kafka", "Docker", "Git"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Database",
        "featured": True,
    },
    {
        "id": "role_data_analyst",
        "title": "Data Analyst",
        "category": "Data",
        "department": "Analytics",
        "difficulty": "Junior",
        "description": "Analyze complex datasets, create dashboards, and deliver actionable business insights.",
        "requiredSkills": ["SQL", "Python", "Data Visualization", "Pandas"],
        "preferredSkills": ["Tableau", "PowerBI", "Excel"],
        "relatedSkills": ["Statistics", "Communication", "Git"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "PieChart",
        "featured": False,
    },
    {
        "id": "role_analytics_eng",
        "title": "Analytics Engineer",
        "category": "Data",
        "department": "Data Platform",
        "difficulty": "Mid-Level",
        "description": "Bridge the gap between data engineering and analysis using dbt and modern data stacks.",
        "requiredSkills": ["SQL", "dbt", "Python", "Data Warehousing"],
        "preferredSkills": ["Snowflake", "BigQuery", "Airflow"],
        "relatedSkills": ["Git", "Data Visualization", "Pandas"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Database",
        "featured": False,
    },
    {
        "id": "role_bi_dev",
        "title": "BI Developer",
        "category": "Data",
        "department": "Analytics",
        "difficulty": "Mid-Level",
        "description": "Design enterprise business intelligence solutions, semantic layers, and reports.",
        "requiredSkills": ["SQL", "PowerBI", "Tableau", "Data Modeling"],
        "preferredSkills": ["Python", "Excel", "Data Warehousing"],
        "relatedSkills": ["Communication", "Git", "Business Analysis"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "LineChart",
        "featured": False,
    },
    {
        "id": "role_db_admin",
        "title": "Database Administrator",
        "category": "Data",
        "department": "Infrastructure",
        "difficulty": "Senior",
        "description": "Manage, tune, and secure massive relational and NoSQL database clusters.",
        "requiredSkills": ["SQL", "PostgreSQL", "Database Administration", "Linux"],
        "preferredSkills": ["MySQL", "MongoDB", "Redis"],
        "relatedSkills": ["Python", "Bash", "Security"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Database",
        "featured": False,
    },
    {
        "id": "role_big_data_eng",
        "title": "Big Data Engineer",
        "category": "Data",
        "department": "Data Platform",
        "difficulty": "Senior",
        "description": "Process petabyte-scale data using Hadoop, Spark, and streaming frameworks.",
        "requiredSkills": ["Java", "Scala", "Apache Spark", "Hadoop"],
        "preferredSkills": ["Kafka", "Python", "AWS"],
        "relatedSkills": ["SQL", "Linux", "Git"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Server",
        "featured": False,
    },
    {
        "id": "role_data_arch",
        "title": "Data Architect",
        "category": "Data",
        "department": "Data Architecture",
        "difficulty": "Staff/Architect",
        "description": "Design enterprise data strategy, governance, and master data management.",
        "requiredSkills": ["System Design", "Data Modeling", "Data Warehousing", "SQL"],
        "preferredSkills": ["AWS", "GCP", "Snowflake"],
        "relatedSkills": ["Python", "Leadership", "Communication"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Brain",
        "featured": False,
    },
    {
        "id": "role_streaming_eng",
        "title": "Data Streaming Engineer",
        "category": "Data",
        "department": "Data Platform",
        "difficulty": "Senior",
        "description": "Build real-time event-driven pipelines and low-latency stream processors.",
        "requiredSkills": ["Java", "Kafka", "Apache Flink", "Python"],
        "preferredSkills": ["Scala", "AWS", "GCP"],
        "relatedSkills": ["SQL", "Docker", "Git"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Cpu",
        "featured": False,
    },
    {
        "id": "role_software_eng",
        "title": "Software Engineer",
        "category": "Software Engineering",
        "department": "Engineering Systems",
        "difficulty": "Mid-Level",
        "description": "Build end-to-end full-lifecycle software solutions focusing on algorithmic efficiency, clean code, and API integration.",
        "requiredSkills": ["Algorithms", "Python", "OOP Design", "REST APIs"],
        "preferredSkills": ["Git", "System Design", "SQL"],
        "relatedSkills": ["Docker", "Testing", "Agile"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Cpu",
        "featured": True,
    },
    {
        "id": "role_dist_sys",
        "title": "Distributed Systems Lead",
        "category": "Software Engineering",
        "department": "Core Infrastructure",
        "difficulty": "Staff/Architect",
        "description": "Design fault-tolerant distributed services, gRPC pipelines, consensus protocols, and event-driven architectures.",
        "requiredSkills": ["Distributed Systems", "Kafka", "System Design", "gRPC"],
        "preferredSkills": ["Go", "Java", "High Availability"],
        "relatedSkills": ["Docker", "Kubernetes", "AWS"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Server",
        "featured": False,
    },
    {
        "id": "role_backend_dev",
        "title": "Backend Developer",
        "category": "Backend",
        "department": "Core Infrastructure",
        "difficulty": "Senior",
        "description": "Architect distributed microservices, robust API contracts, asynchronous event processors, and high-performance databases.",
        "requiredSkills": ["Python", "FastAPI", "PostgreSQL", "System Design"],
        "preferredSkills": ["Docker", "Redis", "Kafka"],
        "relatedSkills": ["Git", "REST APIs", "Testing"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Server",
        "featured": True,
    },
    {
        "id": "role_python_dev",
        "title": "Python Developer",
        "category": "Backend",
        "department": "Backend Applications",
        "difficulty": "Mid-Level",
        "description": "Master core Python mechanics, concurrency, asyncio, typing, testing, and modern frameworks.",
        "requiredSkills": ["Python", "Asyncio", "FastAPI", "Pytest"],
        "preferredSkills": ["SQLAlchemy", "PostgreSQL", "Docker"],
        "relatedSkills": ["Git", "REST APIs", "SQL"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Code",
        "featured": False,
    },
    {
        "id": "role_java_dev",
        "title": "Java Backend Developer",
        "category": "Backend",
        "department": "Enterprise Systems",
        "difficulty": "Senior",
        "description": "Build robust enterprise applications using Java, Spring Boot, and microservices.",
        "requiredSkills": ["Java", "Spring Boot", "Microservices", "SQL"],
        "preferredSkills": ["PostgreSQL", "Docker", "Kafka"],
        "relatedSkills": ["Git", "REST APIs", "Testing"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Code",
        "featured": False,
    },
    {
        "id": "role_go_dev",
        "title": "Golang Developer",
        "category": "Backend",
        "department": "Core Infrastructure",
        "difficulty": "Mid-Level",
        "description": "Write highly concurrent, performant system-level services and microservices in Go.",
        "requiredSkills": ["Go", "Concurrency", "Microservices", "gRPC"],
        "preferredSkills": ["Docker", "Kubernetes", "PostgreSQL"],
        "relatedSkills": ["Git", "REST APIs", "System Design"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Code",
        "featured": False,
    },
    {
        "id": "role_csharp_dev",
        "title": ".NET Developer",
        "category": "Backend",
        "department": "Enterprise Systems",
        "difficulty": "Mid-Level",
        "description": "Develop scalable backend services using C# and .NET Core.",
        "requiredSkills": ["C#", ".NET Core", "SQL Server", "REST APIs"],
        "preferredSkills": ["Azure", "Microservices", "Docker"],
        "relatedSkills": ["Git", "Testing", "OOP Design"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Code",
        "featured": False,
    },
    {
        "id": "role_node_dev",
        "title": "Node.js Developer",
        "category": "Backend",
        "department": "Web Backend",
        "difficulty": "Mid-Level",
        "description": "Build asynchronous backend APIs and real-time services using Node.js and Express/NestJS.",
        "requiredSkills": ["Node.js", "TypeScript", "Express", "REST APIs"],
        "preferredSkills": ["NestJS", "MongoDB", "PostgreSQL"],
        "relatedSkills": ["Git", "Docker", "Redis"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Code",
        "featured": False,
    },
    {
        "id": "role_cpp_eng",
        "title": "C++ Software Engineer",
        "category": "Software Engineering",
        "department": "High Performance",
        "difficulty": "Senior",
        "description": "Develop ultra-low latency systems, game engines, or high-frequency trading platforms.",
        "requiredSkills": ["C++", "Memory Management", "Algorithms", "Concurrency"],
        "preferredSkills": ["Linux", "CMake", "Python"],
        "relatedSkills": ["Git", "System Design", "Networking"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Cpu",
        "featured": False,
    },
    {
        "id": "role_rust_eng",
        "title": "Rust Developer",
        "category": "Software Engineering",
        "department": "Core Infrastructure",
        "difficulty": "Senior",
        "description": "Build safe, concurrent, and blazing-fast systems software in Rust.",
        "requiredSkills": ["Rust", "Concurrency", "Memory Safety", "System Programming"],
        "preferredSkills": ["Linux", "WebAssembly", "C++"],
        "relatedSkills": ["Git", "Docker", "Algorithms"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Code",
        "featured": False,
    },
    {
        "id": "role_api_eng",
        "title": "API Engineer",
        "category": "Backend",
        "department": "Platform",
        "difficulty": "Mid-Level",
        "description": "Design developer-friendly REST and GraphQL APIs with strict contracts and high performance.",
        "requiredSkills": ["REST APIs", "GraphQL", "Python", "API Design"],
        "preferredSkills": ["Node.js", "PostgreSQL", "FastAPI"],
        "relatedSkills": ["Git", "Docker", "Testing"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Server",
        "featured": False,
    },
    {
        "id": "role_sys_arch",
        "title": "Systems Architect",
        "category": "Software Engineering",
        "department": "Architecture",
        "difficulty": "Staff/Architect",
        "description": "Define technical vision, architecture patterns, and scale services to millions of users.",
        "requiredSkills": ["System Design", "Microservices", "Cloud Architecture", "Distributed Systems"],
        "preferredSkills": ["AWS", "GCP", "Kubernetes"],
        "relatedSkills": ["Leadership", "Communication", "Security"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Brain",
        "featured": False,
    },
    {
        "id": "role_gaming_eng",
        "title": "Game Developer",
        "category": "Software Engineering",
        "department": "Gaming",
        "difficulty": "Mid-Level",
        "description": "Build immersive 3D games and optimize rendering engines.",
        "requiredSkills": ["C++", "C#", "Unity", "Unreal Engine"],
        "preferredSkills": ["3D Math", "Graphics Programming", "Physics"],
        "relatedSkills": ["Git", "Algorithms", "Optimization"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Monitor",
        "featured": False,
    },
    {
        "id": "role_embedded_eng",
        "title": "Embedded Systems Engineer",
        "category": "Software Engineering",
        "department": "Hardware",
        "difficulty": "Senior",
        "description": "Write firmware and RTOS applications for microcontrollers and IoT devices.",
        "requiredSkills": ["C", "C++", "Embedded Systems", "RTOS"],
        "preferredSkills": ["Linux", "Python", "Hardware Debugging"],
        "relatedSkills": ["Git", "IoT", "Networking"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Cpu",
        "featured": False,
    },
    {
        "id": "role_fe_arch",
        "title": "Senior Frontend Architect",
        "category": "Frontend & Fullstack",
        "department": "Web Engineering",
        "difficulty": "Senior",
        "description": "Lead the architecture, design tokens, and performance of enterprise React applications.",
        "requiredSkills": ["React", "TypeScript", "Design Systems", "Web Vitals"],
        "preferredSkills": ["Next.js", "Micro-Frontends", "CSS"],
        "relatedSkills": ["Git", "Testing", "JavaScript"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Layout",
        "featured": True,
    },
    {
        "id": "role_fe_dev",
        "title": "Frontend Developer",
        "category": "Frontend & Fullstack",
        "department": "Web Engineering",
        "difficulty": "Mid-Level",
        "description": "Create highly interactive, responsive, and accessible user interfaces.",
        "requiredSkills": ["JavaScript", "React", "CSS", "HTML"],
        "preferredSkills": ["TypeScript", "Tailwind CSS", "Redux"],
        "relatedSkills": ["Git", "UI/UX", "REST APIs"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Layout",
        "featured": False,
    },
    {
        "id": "role_fullstack_dev",
        "title": "Fullstack Developer",
        "category": "Frontend & Fullstack",
        "department": "Product Engineering",
        "difficulty": "Mid-Level",
        "description": "Deliver end-to-end features spanning databases, APIs, and user interfaces.",
        "requiredSkills": ["JavaScript", "React", "Node.js", "PostgreSQL"],
        "preferredSkills": ["TypeScript", "Python", "Docker"],
        "relatedSkills": ["Git", "REST APIs", "CSS"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Monitor",
        "featured": True,
    },
    {
        "id": "role_angular_dev",
        "title": "Angular Developer",
        "category": "Frontend & Fullstack",
        "department": "Enterprise Web",
        "difficulty": "Mid-Level",
        "description": "Build robust enterprise single-page applications using Angular and RxJS.",
        "requiredSkills": ["Angular", "TypeScript", "RxJS", "HTML"],
        "preferredSkills": ["CSS", "NgRx", "Jasmine"],
        "relatedSkills": ["Git", "REST APIs", "JavaScript"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Layout",
        "featured": False,
    },
    {
        "id": "role_vue_dev",
        "title": "Vue.js Developer",
        "category": "Frontend & Fullstack",
        "department": "Web Engineering",
        "difficulty": "Mid-Level",
        "description": "Develop reactive web applications using Vue.js and Nuxt.",
        "requiredSkills": ["Vue.js", "JavaScript", "CSS", "HTML"],
        "preferredSkills": ["TypeScript", "Nuxt.js", "Vuex"],
        "relatedSkills": ["Git", "REST APIs", "UI/UX"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Layout",
        "featured": False,
    },
    {
        "id": "role_mobile_ios",
        "title": "iOS Developer",
        "category": "Frontend & Fullstack",
        "department": "Mobile",
        "difficulty": "Mid-Level",
        "description": "Build native iOS applications using Swift and SwiftUI.",
        "requiredSkills": ["Swift", "iOS", "SwiftUI", "Xcode"],
        "preferredSkills": ["Objective-C", "Core Data", "REST APIs"],
        "relatedSkills": ["Git", "UI/UX", "Testing"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Smartphone",
        "featured": False,
    },
    {
        "id": "role_mobile_android",
        "title": "Android Developer",
        "category": "Frontend & Fullstack",
        "department": "Mobile",
        "difficulty": "Mid-Level",
        "description": "Develop high-performance native Android applications using Kotlin.",
        "requiredSkills": ["Kotlin", "Android SDK", "Jetpack Compose", "Android Studio"],
        "preferredSkills": ["Java", "Coroutines", "REST APIs"],
        "relatedSkills": ["Git", "UI/UX", "Testing"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Smartphone",
        "featured": False,
    },
    {
        "id": "role_mobile_rn",
        "title": "React Native Developer",
        "category": "Frontend & Fullstack",
        "department": "Mobile",
        "difficulty": "Mid-Level",
        "description": "Build cross-platform mobile apps using React Native.",
        "requiredSkills": ["React Native", "JavaScript", "TypeScript", "Mobile App Development"],
        "preferredSkills": ["React", "Redux", "REST APIs"],
        "relatedSkills": ["Git", "UI/UX", "iOS/Android"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Smartphone",
        "featured": False,
    },
    {
        "id": "role_mobile_flutter",
        "title": "Flutter Developer",
        "category": "Frontend & Fullstack",
        "department": "Mobile",
        "difficulty": "Mid-Level",
        "description": "Create beautiful compiled cross-platform apps with Flutter and Dart.",
        "requiredSkills": ["Flutter", "Dart", "Mobile App Development", "UI/UX"],
        "preferredSkills": ["Firebase", "REST APIs", "State Management"],
        "relatedSkills": ["Git", "Testing", "Animations"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Smartphone",
        "featured": False,
    },
    {
        "id": "role_devops_eng",
        "title": "DevOps Engineer",
        "category": "Cloud & DevOps",
        "department": "Platform Engineering",
        "difficulty": "Senior",
        "description": "Bridge development and operations with CI/CD, infrastructure as code, and automation.",
        "requiredSkills": ["CI/CD", "Docker", "Kubernetes", "Terraform"],
        "preferredSkills": ["AWS", "Linux", "Python"],
        "relatedSkills": ["Git", "Bash", "Monitoring"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Server",
        "featured": True,
    },
    {
        "id": "role_cloud_arch",
        "title": "Cloud Solutions Architect",
        "category": "Cloud & DevOps",
        "department": "Cloud Engineering",
        "difficulty": "Staff/Architect",
        "description": "Design secure, scalable, and highly available cloud-native architectures.",
        "requiredSkills": ["AWS", "Cloud Architecture", "System Design", "Networking"],
        "preferredSkills": ["GCP", "Azure", "Kubernetes"],
        "relatedSkills": ["Terraform", "Security", "Leadership"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Cloud",
        "featured": True,
    },
    {
        "id": "role_sre",
        "title": "Site Reliability Engineer (SRE)",
        "category": "Cloud & DevOps",
        "department": "Platform Engineering",
        "difficulty": "Senior",
        "description": "Apply software engineering to operations to ensure system reliability and uptime.",
        "requiredSkills": ["Linux", "Python", "Kubernetes", "Monitoring"],
        "preferredSkills": ["Go", "Terraform", "AWS"],
        "relatedSkills": ["Incident Management", "Docker", "Networking"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Server",
        "featured": False,
    },
    {
        "id": "role_platform_eng",
        "title": "Platform Engineer",
        "category": "Cloud & DevOps",
        "department": "Internal Developer Platform",
        "difficulty": "Senior",
        "description": "Build internal tooling and paved roads to accelerate developer productivity.",
        "requiredSkills": ["Kubernetes", "Go", "CI/CD", "Docker"],
        "preferredSkills": ["Python", "Terraform", "AWS"],
        "relatedSkills": ["Git", "System Design", "Linux"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Cpu",
        "featured": False,
    },
    {
        "id": "role_finops",
        "title": "Cloud FinOps Engineer",
        "category": "Cloud & DevOps",
        "department": "Cloud Engineering",
        "difficulty": "Mid-Level",
        "description": "Optimize cloud infrastructure costs, track usage, and manage resource lifecycle.",
        "requiredSkills": ["AWS", "Cloud Architecture", "Cost Optimization", "Data Analysis"],
        "preferredSkills": ["Python", "SQL", "Terraform"],
        "relatedSkills": ["Communication", "Linux", "Monitoring"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "LineChart",
        "featured": False,
    },
    {
        "id": "role_release_eng",
        "title": "Release Engineer",
        "category": "Cloud & DevOps",
        "department": "Platform Engineering",
        "difficulty": "Mid-Level",
        "description": "Manage complex software release pipelines and deployment strategies.",
        "requiredSkills": ["CI/CD", "Git", "Bash", "Python"],
        "preferredSkills": ["Docker", "Linux", "Jenkins"],
        "relatedSkills": ["Agile", "Communication", "Testing"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Code",
        "featured": False,
    },
    {
        "id": "role_sec_eng",
        "title": "Security Engineer",
        "category": "Security & Specialty",
        "department": "Cybersecurity",
        "difficulty": "Senior",
        "description": "Secure infrastructure, perform penetration testing, and build threat detection systems.",
        "requiredSkills": ["Cybersecurity", "Network Security", "Python", "Linux"],
        "preferredSkills": ["AWS Security", "Penetration Testing", "Cryptography"],
        "relatedSkills": ["Bash", "Docker", "System Design"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Shield",
        "featured": True,
    },
    {
        "id": "role_app_sec",
        "title": "Application Security Engineer",
        "category": "Security & Specialty",
        "department": "Cybersecurity",
        "difficulty": "Senior",
        "description": "Audit code, integrate security in CI/CD (DevSecOps), and guide secure coding.",
        "requiredSkills": ["Application Security", "OWASP", "Python", "CI/CD"],
        "preferredSkills": ["JavaScript", "Java", "Go"],
        "relatedSkills": ["Git", "Docker", "Code Review"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Lock",
        "featured": False,
    },
    {
        "id": "role_blockchain_eng",
        "title": "Blockchain Engineer",
        "category": "Security & Specialty",
        "department": "Web3",
        "difficulty": "Senior",
        "description": "Develop smart contracts, decentralized apps, and crypto protocols.",
        "requiredSkills": ["Solidity", "Blockchain", "Cryptography", "Smart Contracts"],
        "preferredSkills": ["Ethereum", "Rust", "Web3.js"],
        "relatedSkills": ["Python", "System Design", "Security"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Key",
        "featured": False,
    },
]
