"""
Role catalogue — single source of truth for available interview roles.
The 'title' field is what gets sent to the LangGraph interview engine as `role`.
"""

from typing import List, Dict, Any

ROLE_CATALOGUE: List[Dict[str, Any]] = [
    {
        "id": "role_ml_eng",
        "title": "ML Engineer",
        "department": "Machine Learning & AI",
        "difficulty": "Senior",
        "description": "Design and deploy state-of-the-art machine learning models, vector pipelines, and evaluation engines with PyTorch and FastAPI.",
        "requiredSkills": ["Python", "Machine Learning", "PyTorch", "Scikit-learn", "FastAPI"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Brain",
        "featured": True,
    },
    {
        "id": "role_backend_dev",
        "title": "Backend Developer",
        "department": "Core Infrastructure",
        "difficulty": "Senior",
        "description": "Architect distributed microservices, robust API contracts, asynchronous event processors, and high-performance databases.",
        "requiredSkills": ["Python", "FastAPI", "PostgreSQL", "Docker", "System Design"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Server",
        "featured": True,
    },
    {
        "id": "role_software_eng",
        "title": "Software Engineer",
        "department": "Engineering Systems",
        "difficulty": "Mid-Level",
        "description": "Build end-to-end full-lifecycle software solutions focusing on algorithmic efficiency, clean code, and API integration.",
        "requiredSkills": ["Algorithms", "Python", "OOP Design", "REST APIs", "Git"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Cpu",
        "featured": True,
    },
    {
        "id": "role_python_dev",
        "title": "Python Developer",
        "department": "Backend Applications",
        "difficulty": "Mid-Level",
        "description": "Master core Python mechanics, concurrency, asyncio, typing, testing, and modern frameworks like FastAPI and Pydantic.",
        "requiredSkills": ["Python 3.12", "Asyncio", "FastAPI", "Pytest", "SQLAlchemy"],
        "estimatedTimeMinutes": 25,
        "questionCount": 5,
        "iconName": "Code",
        "featured": False,
    },
    {
        "id": "role_data_scientist",
        "title": "Data Scientist",
        "department": "Analytics & Modeling",
        "difficulty": "Senior",
        "description": "Drive actionable predictive modeling, statistical hypothesis testing, feature engineering, and metric attribution.",
        "requiredSkills": ["Statistics", "Python", "Pandas", "Scikit-learn", "SQL"],
        "estimatedTimeMinutes": 35,
        "questionCount": 5,
        "iconName": "LineChart",
        "featured": False,
    },
    {
        "id": "role_fe_arch",
        "title": "Senior Frontend Architect",
        "department": "Web Engineering",
        "difficulty": "Senior",
        "description": "Lead the architecture, design tokens, and performance of enterprise React 18 applications with high concurrency.",
        "requiredSkills": ["React", "TypeScript", "Design Systems", "Micro-Frontends", "Web Vitals"],
        "estimatedTimeMinutes": 30,
        "questionCount": 5,
        "iconName": "Layout",
        "featured": False,
    },
    {
        "id": "role_dist_sys",
        "title": "Distributed Systems Lead",
        "department": "Core Infrastructure",
        "difficulty": "Staff/Architect",
        "description": "Design fault-tolerant distributed services, gRPC pipelines, consensus protocols, and event-driven architectures.",
        "requiredSkills": ["Distributed Systems", "Kafka", "System Design", "gRPC", "High Availability"],
        "estimatedTimeMinutes": 45,
        "questionCount": 5,
        "iconName": "Cpu",
        "featured": False,
    },
]
